"""
Contains a list of insult templates and other textual elements.
"""

import random

# Insult templates
insult_templates = [
    "Hey {name}, your secrets are always safe with your friends. They never remember them anyway.",
    "{name}, the only thing you're good at is being yourself. And that's not exactly a compliment.",
    "I've had coffee mugs smarter than you, {name}.",
    "Somewhere out there, there's a tree working tirelessly to replace the oxygen you wasted, {name}.",
    "I'm not saying you're stupid, {name}, but you'd lose a battle of wits against an unarmed opponent.",
    "If laughter is the best medicine, your face must be curing the world, {name}.",
    "Mirrors can't talk, lucky for you, {name}. They also can't laugh, which gives them another advantage over you.",
    "{name}, you're proof that evolution can go in reverse.",
    "{name}, I'm not sure what's tighter, your jeans or your grip on reality.",
    "I'd agree with you, {name}, but then we'd both be wrong.",
    "Is your brain made of sponges, {name}? Because it seems to soak up everything but knowledge.",
    "{name}, you're like a broken pencil – pointless.",
    "I'm surprised you can walk and chew gum at the same time, {name}.",
    "You're so dense, {name}, light bends around you.",
    "I'm not saying you're lazy, {name}, but if there was an award for doing nothing, you'd send someone to pick it up for you.",
    "{name}, I've had enough of you. I'm going to need a few days off to recover.",
    "Your childhood must have been a fall down the stairs, {name}.",
    "I've seen garden slugs with more charisma than you, {name}.",
    "You bring everyone so much joy, {name}, when you leave the room.",
    "I'm not sure what's worse, your breath or your personality, {name}.",
    "If you were any slower, {name}, you'd be going backwards.",
    "You're so fake, {name}, Barbie is jealous.",
    "{name}, your mind makes mine feel like a tourist attraction.",
    "I'm not insulting you, {name}, I'm describing you.",
    "You're so full of hot air, {name}, you could be a weather balloon.",
    "I'd call you a tool, {name}, but even tools have a purpose.",
    "You're so transparent, {name}, I can see right through your lies.",
    "I'm not saying you're ugly, {name}, but you could scare a werewolf.",
    "You're like a black hole, {name}, you suck the joy out of everything.",
    "I've had conversations with rocks that were more stimulating, {name}.",
    "You're so forgettable, {name}, I've already forgotten you.",
    "I'd rather have a root canal than talk to you, {name}.",
    "You're so useless, {name}, you're like a white crayon.",
    "I'm not saying you're a bad person, {name}, but you'd fail a Rorschach test.",
    "You're so predictable, {name}, I can finish your sentences.",
    "I'd rather be a fish out of water than be around you, {name}.",
    "You're so dull, {name}, you make dishwater look exciting.",
    "I'm not saying you're a loser, {name}, but you'd lose in a game of solitaire.",
    "You're so two-faced, {name}, you could be a coin.",
    "I'd rather have a paper cut on my eyeball than listen to you, {name}.",
    "You're so dense, {name}, you could be a neutron star.",
    "I'm not saying you're annoying, {name}, but you'd irritate a saint.",
    "You're so clumsy, {name}, you could trip over a wireless connection.",
    "I'd rather have a cactus hug than a conversation with you, {name}.",
    "You're so slow, {name}, you could be a snail on tranquilizers.",
    "I'm not saying you're a moron, {name}, but you'd fail a mirror test.",
    "You're so insignificant, {name}, you're like a grain of sand on a beach.",
    "I'd rather have a mosquito bite than see your face, {name}.",
    "You're so boring, {name}, you could put a caffeine addict to sleep.",
    "I'm not saying you're a waste of space, {name}, but you'd make a black hole feel crowded.",
    "You're so forgetful, {name}, you'd forget your own birthday.",
    "I'd rather have a hangnail than hear your opinion, {name}.",
    "You're so useless, {name}, you're like a screen door on a submarine.",
    "I'm not saying you're a disgrace, {name}, but you'd make a garbage dump look glamorous.",
    "You're so predictable, {name}, you're like a broken record.",
    "I'd rather have a head cold than deal with you, {name}.",
    "You're so dense, {name}, you could be a brick wall.",
    "I'm not saying you're a pest, {name}, but you'd make a fly feel welcome.",
    "You're so clumsy, {name}, you could trip over your own shadow.",
    "I'd rather have a splinter in my tongue than talk to you, {name}.",
    "You're so slow, {name}, you could be a sloth on vacation.",
    "I'm not saying you're a nitwit, {name}, but you'd fail a test designed for rocks.",
    "You're so insignificant, {name}, you're like a dust mite in a hurricane.",
    "I'd rather have a paper cut on my soul than see your face, {name}.",
    "You're so boring, {name}, you could put a narcoleptic to sleep.",
    "I'm not saying you're a waste of oxygen, {name}, but you'd make a plant feel suffocated.",
    "You're so forgetful, {name}, you'd forget your own name.",
    "I'd rather have a root canal without anesthesia than hear your opinion, {name}.",
    "You're so useless, {name}, you're like a chocolate teapot.",
    "I'm not saying you're a disgrace to humanity, {name}, but you'd make a landfill look like a garden.",
    "You're so predictable, {name}, you're like a broken clock.",
    "I'd rather have a head cold and a toothache than deal with you, {name}.",
    "You're so dense, {name}, you could be a black hole of stupidity.",
    "I'm not saying you're a pest to society, {name}, but you’d make a mosquito feel charitable.",
    "You're so clumsy, {name}, you could start a fire in a water park.",
    "I'd rather have a splinter in my brain than talk to you, {name}.",
    "You're so slow, {name}, you could be a glacier in July.",
    "I'm not saying you're a dimwit, {name}, but you'd fail a test designed for amoebas.",
    "You're so insignificant, {name}, you're like a subatomic particle in the universe.",
    "I'd rather have a paper cut on my funny bone than see your face, {name}.",
    "You're so boring, {name}, you could put a caffeine addict in a coma.",
    "I'm not saying you're a waste of carbon dioxide, {name}, but you’d make a rainforest feel barren.",
    "You're so forgetful, {name}, you’d forget your own address.",
    "I'd rather have a root canal without novocaine than hear your opinion, {name}.",
    "You're so useless, {name}, you’re like a screen door on a submarine during a hurricane.",
    "I'm not saying you're a disgrace to the planet, {name}, but you’d make a toxic waste dump look pristine.",
    "You're so predictable, {name}, you’re like a broken record on repeat.",
    "I'd rather have a head cold, a toothache, and a hangnail than deal with you, {name}.",
    "You're so dense, {name}, you could be a black hole of utter stupidity.",
    "You're like a cloud, {name}. When you disappear, it's a beautiful day.",
    "I'm not saying you're annoying, {name}, but I'd rather listen to a dial-up modem.",
    "You're so slow, {name}, I've seen turtles going to a sprint.",
    "Is your brain a fish tank, {name}? Empty and full of green stuff?",
    "You're so bad at everything, {name}, you make mediocrity look impressive.",
    "I'm not saying you're stupid, {name}, but you'd struggle with a one-piece puzzle.",
    "You're so fake, {name}, even China refused to make you.",
    "You're so full of yourself, {name}, you'd need a crane to lift your ego.",
    "I'm not saying you're ugly, {name}, but your face would make onions cry.",
    "You're so forgettable, {name}, you're like the appendix of people.",
    "You're so useless, {name}, you're like a broken pen without ink.",
    "I'm not saying you're a bad influence, {name}, but you'd make a devil blush.",
    "You're so predictable, {name}, even a fortune cookie has more surprises.",
    "You're so boring, {name}, you could make a rock collection exciting.",
    "I'm not saying you're a waste of time, {name}, but you'd make a snail feel rushed.",
    "You're so dense, {name}, you'd make a brick wall feel weightless.",
    "You're so slow, {name}, you'd lose a race against a sloth.",
    "I'm not saying you're a nitwit, {name}, but you'd fail a test designed for plants.",
    "You're so insignificant, {name}, you're like a single grain of sand on a planet-sized beach.",
    "You're so forgetful, {name}, you'd forget to breathe if you weren't reminded.",
    "You're so useless, {name}, you're like a screen door on a submarine during a flood.",
    "You're so predictable, {name}, you're like a broken record stuck on repeat.",
    "You're so boring, {name}, you could put a caffeine addict in a coma during a rock concert.",
    "You're so dense, {name}, you'd make a black hole feel spacious.",
    "You're so slow, {name}, you'd lose a race against a snail during a nap.",
    "I'm not saying you're a moron, {name}, but you'd fail a test designed for single-celled organisms.",
    "You're so forgetful, {name}, you'd forget your own name in a conversation.",
    "You're so useless, {name}, you're like a chocolate teapot in a desert.",
    "You're so predictable, {name}, you're like a broken clock that's always wrong.",
    "You're so boring, {name}, you could put a caffeine addict in a coma during a rock concert in a library.",
    "You're so dense, {name}, you'd make a black hole feel like a spacious apartment.",
    "You're so slow, {name}, you'd lose a race against a snail during a nap on a treadmill.",
    "You're so forgetful, {name}, you'd forget your own name in a conversation with yourself.",
    "You're so useless, {name}, you’re like a chocolate teapot in a desert during a heat wave.",
    "You're so predictable, {name}, you’re like a broken clock that's always wrong and loud.",
    "You’re so boring, {name}, you could put a caffeine addict in a coma during a rock concert in a library during a lecture on sleep.",
    "You’re so dense, {name}, you could make a black hole feel like a spacious apartment with a view of the universe.",
    "You’re so slow, {name}, you’d lose a race against a snail during a nap on a treadmill going backwards.",
    "You’re so forgetful, {name}, you’d forget your own name in a conversation with yourself while looking in a mirror.",
    "You’re so useless, {name}, you’re like a chocolate teapot in a desert during a heat wave while it’s raining chocolate.",
    "You’re so predictable, {name}, you’re like a broken clock that’s always wrong and loud and annoying.",
    "You’re so boring, {name}, you could put a caffeine addict in a coma during a rock concert in a library during a lecture on sleep while watching paint dry.",
    "You’re so dense, {name}, you’d make a black hole feel like a spacious apartment with a view of the universe while it’s expanding.",
    "You’re so slow, {name}, you’d lose a race against a snail during a nap on a treadmill going backwards while it’s stuck in molasses.",
    "You’re so forgetful, {name}, you’d forget your own name in a conversation with yourself while looking in a mirror and trying to remember what you were saying.",
    "You’re so useless, {name}, you’re like a chocolate teapot in a desert during a heat wave while it’s raining chocolate and you’re trying to make tea.",
    "You’re so predictable, {name}, you’re like a broken clock that’s always wrong and loud and annoying and also on fire.",
    "You’re so boring, {name}, you could put a caffeine addict in a coma during a rock concert in a library during a lecture on sleep while watching paint dry and listening to elevator music.",
    "You’re so dense, {name}, you’d make a black hole feel like a spacious apartment with a view of the universe while it’s expanding and you’re trying to find your keys.",
    "You’re so slow, {name}, you’d lose a race against a snail during a nap on a treadmill going backwards while it’s stuck in molasses and you’re wearing lead boots.",
    "You’re so forgetful, {name}, you’d forget your own name in a conversation with yourself while looking in a mirror and trying to remember what you were saying and also why you’re in the bathroom.",
    "You’re so useless, {name}, you’re like a chocolate teapot in a desert during a heat wave while it’s raining chocolate and you’re trying to make tea and also you’re on fire.",
    "You’re so predictable, {name}, you’re like a broken clock that’s always wrong and loud and annoying and also on fire and also you’re trying to fix it.",
    "You’re so boring, {name}, you could put a caffeine addict in a coma during a rock concert in a library during a lecture on sleep while watching paint dry and listening to elevator music and also you’re trying to explain quantum physics.",
    "You’re so dense, {name}, you’d make a black hole feel like a spacious apartment with a view of the universe while it’s expanding and you’re trying to find your keys and also you’re wearing a spacesuit.",
    "You’re so slow, {name}, you’d lose a race against a snail during a nap on a treadmill going backwards while it’s stuck in molasses and you’re wearing lead boots and also you’re trying to read a book.",
    "You’re so forgetful, {name}, you’d forget your own name in a conversation with yourself while looking in a mirror and trying to remember what you were saying and also why you’re in the bathroom and also you’re trying to remember what you had for breakfast.",
    "You’re so useless, {name}, you’re like a chocolate teapot in a desert during a heat wave while it’s raining chocolate and you’re trying to make tea and also you’re on fire and also you’re trying to put out the fire with the tea.",
    "You’re so predictable, {name}, you’re like a broken clock that’s always wrong and loud and annoying and also on fire and also you’re trying to fix it with a hammer.",
    "You’re so boring, {name}, you could put a caffeine addict in a coma during a rock concert in a library during a lecture on sleep while watching paint dry and listening to elevator music and also you’re trying to explain quantum physics to a goldfish.",
    "You’re so dense, {name}, you’d make a black hole feel like a spacious apartment with a view of the universe while it’s expanding and you’re trying to find your keys and also you’re wearing a spacesuit and also you’re trying to parallel park.",
    "You’re so slow, {name}, you’d lose a race against a snail during a nap on a treadmill going backwards while it’s stuck in molasses and you’re wearing lead boots and also you’re trying to read a book and also you’re trying to solve a Rubik’s Cube.",
    "You’re so forgetful, {name}, you’d forget your own name in a conversation with yourself while looking in a mirror and trying to remember what you were saying and also why you’re in the bathroom and also you’re trying to remember what you had for breakfast and also you’re trying to remember what day it is."
]

# Greeting templates
greeting_templates = [
    f"Dear {{name}},",
    f"To the ever-mediocre {{name}},",
    f"Hello {{name}}, though I use 'hello' loosely...",
    f"Hey {{name}}, prepare yourself...",
    f"Greetings, {{name}},",
] + [f"Salutations, {{name}} the Unremarkable," for _ in range(45)]

# Company names
company_names = [
    "Disrespect Dynamics Inc.",
    "Mockery & Sons",
    "The Insult Bureau",
    "Petty & Professional Co.",
    "Ego Crushers Unlimited",
    "Obfuscation Incorporated",
    "SnideTech Solutions",
    "Sarcasm & Co.",
    "The Bureau of Backhanded Affairs",
    "Global Disappointment Authority",
    "Ministry of Mockery",
    "ContemptCorp",
    "Shenanigan Strategies",
    "PassiveAggro Partners",
    "Department of Mild Insults",
    "Institute of Offense Engineering",
    "The League of Petty Remarks",
    "Irony International",
    "The Condescension Collective",
    "Flimflam Federation",
    "Mockery Metrics Ltd.",
    "Eyeroll Enterprises",
    "SneerWorks",
    "Bureau of Tactical Roasting",
    "Committee of Corporate Sarcasm",
    "Petty & Vicious, LLP",
    "The Snark Syndicate",
    "ToneDown Technologies",
    "Eye Roll Research Group",
    "Global Ridicule Systems",
    "Disdain Unlimited",
    "Verbal Volley Corp",
    "Just Kidding Holdings",
    "Snub & Subtle Inc.",
    "The Slight Society",
    "Snarkitecture Inc.",
    "SideEye Studios",
    "The Miscommunication Agency",
    "Awkward Silence Group",
    "The House of Hollow Praise",
    "OopsWeInsultedYou Inc.",
    "Superficial Praise Bureau",
    "You Tried Technologies",
    "The Null Compliments Division",
    "Bureau of Emotional Damage",
    "Tactless Titans",
    "Third-Degree Burn Enterprises",
    "The Dry Remark Collective",
    "Oops & Co.",
    "The Casual Burn Chamber",
    "Don't Quote Us Consulting",
    "Department of Verbal Acrobatics",
    "Bitter & Sharp Inc.",
    "Thank You, Next Ltd.",
    "Your Feedback Matters Inc.",
] + [f"{adj} {noun} Corporation" for adj in [
    "Absurd", "Disdainful", "Sarcastic", "Petty", "Contemptuous",
    "Apathetic", "Ironical", "Scornful", "Disrespectful", "Flippant"
] for noun in [
    "Solutions", "Ventures", "Industries", "Dynamics", "Group"
]][:50]

# Titles
title_templates = [
    "Senior Insult Architect",
    "Global Director of Snark",
    "Executive VP of Verbal Evisceration",
    "Certified Sass Distributor",
    "Mockery Consultant, Level 99",
    "Executive Director of Disdain",
    "Vice President of Viciousness",
    "Senior Manager of Mockery",
    "Chief Sarcasm Officer",
    "Director of Snide Operations",
    "Associate of Absurdity",
    "CFO (Chief Flaming Officer)",
    "Coordinator of Caustic Communication",
    "Principal of Petty Affairs",
    "Insult Innovation Consultant",
    "Lead Engineer of Eyerolls",
    "Director of Roasting Relations",
    "Head of Haughty Remarks",
    "Public Relations Menace",
    "Manager of Malicious Compliments",
    "Compliments Control Officer",
    "Snide Response Supervisor",
    "Chair of Mockery Mechanics",
    "Director of Shady Deals and Zingers",
    "International Ambassador of Sass",
    "Regional Chief of Witty Retorts",
    "Permanent Representative of Sarcasm",
    "Department Head of Subtle Hostility",
    "Chief Banter Strategist",
    "Principal of Passive Aggression",
    "VP of Veiled Insults",
    "Team Lead for Tactical Taunts",
    "Senior Analyst of Irony",
    "Compliment Contradiction Manager",
    "Chief Executive Snarker",
    "Strategy Lead, Department of Not Sorry",
    "Head of Unsolicited Opinions",
    "Director of Half-Hearted Praise",
    "Bureau Chief of Disrespectful Discourse",
    "Culture and Sass Officer",
    "Manager of Occasional Truth Bombs",
    "Vice Chair of Laughable Leadership",
    "Creative Director of Insult Delivery",
    "Lead Mockery Facilitator",
    "Coordinator of Unhelpful Feedback",
    "Specialist in Accidental Compliments",
    "Senior Specialist, Feedback That Hurts",
    "Executive Officer of Brutal Honesty",
    "Chief Clapback Consultant",
    "Professional Underminer",
    "Commander of Complicated Apologies",
    "Group Lead of Rhetorical Smirks",
    "Founding Member, Council of Sass",
    "Global Strategist for Misdirected Praise",
    "Resident Ironist",
] + [f"{role} of {division}" for role in [
    "Coordinator", "Manager", "Specialist", "Head", "Chief"
] for division in [
    "Petty Affairs", "Subtle Jabs", "Sarcasm Solutions",
    "Ridicule Distribution", "Passive Aggression"
]][:50]

# Signatures
signature_templates = [
    "Wishing you nothing but mediocrity,",
    "In relentless sarcasm,",
    "Yours in eternal roast,",
    "Stay underwhelming,",
    "Professionally insincere,",
    "Sincerely Yours,",
    "With Regards,",
    "Best Regards,",
    "Warmly,",
    "Respectfully,",
    "Cheers,",
    "Yours in Insincerity,",
    "With Mocking Affection,",
    "Professionally Insincere,",
    "Sarcastically Yours,",
    "Yours in Disdain,",
    "In Gratitude for Your Eyerolls,",
    "All the Best (Not Really),",
    "Condescendingly Yours,",
    "Yours in Mild Displeasure,",
    "With Smirking Delight,",
    "With Slight Contempt,",
    "With a Side of Eyeroll,",
    "Yours with a Grin,",
    "In Your Best Interests (Maybe),",
    "Amicably Yours,",
    "With a Sigh of Disappointment,",
    "Unapologetically Yours,",
    "Smugly,",
    "In a Completely Non-Helpful Manner,",
    "With a Wink and a Nod,",
    "With Disdainful Approval,",
    "Yours in Passive Aggression,",
    "Yours While Rolling My Eyes,",
    "At Your Service (Kind of),",
    "Yours as a Last Resort,",
    "With Sarcastic Delight,",
    "From the Desk of Derision,",
    "Uninspiredly Yours,",
    "From Your Favorite Disappointing Person,",
    "With Just the Right Amount of Discomfort,",
    "The Audacity of Yours Truly,",
    "Gratefully Yours,",
    "Sarcastically Yours (Again),",
    "Eyerollingly Yours,",
    "From One Mildly Amused to Another,",
    "Mildly Enthusiastically,",
    "With More Than a Hint of Sarcasm,",
    "Rolling My Eyes,",
    "With Dignified Disrespect,",
    "Yours Indifferently,",
    "Utterly Unimpressed,",
] + [f"In {adj} regards," for adj in [
    "underwhelming", "half-hearted", "lukewarm",
    "unimpressed", "emotionally distant"
] * 10][:50]

# Functions to fetch random entries
def get_random_greeting(name: str) -> str:
    return random.choice(greeting_templates).format(name=name)

def get_random_insult(name: str) -> str:
    return random.choice(insult_templates).format(name=name)

def get_random_company() -> str:
    return random.choice(company_names)

def get_random_title() -> str:
    return random.choice(title_templates)

def get_random_signature() -> str:
    return random.choice(signature_templates)